version: '3.8'
services:
  web:
    build: .
    restart: always
    ports:
     - "8000:8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    depends_on:
      - web