# Generated by Django 4.1.1 on 2022-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара', max_length=255, verbose_name='Наименование товара')),
                ('description', models.TextField(help_text='Описание товара', verbose_name='Описание товара')),
                ('price', models.PositiveSmallIntegerField(help_text='Цена товара', verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveSmallIntegerField(help_text='Общая цена товаров в заказе', verbose_name='Цена товаров')),
                ('items', models.ManyToManyField(related_name='Товары', to='items.item')),
            ],
        ),
    ]
