# Generated by Django 4.1.3 on 2022-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_discount_order_remove_iteminorder_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Описание товара', null=True, verbose_name='Описание товара'),
        ),
    ]
