# Generated by Django 4.1.3 on 2022-11-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_description'),
        ('order', '0002_alter_iteminorder_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminorder',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='tax',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='order.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteminorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='items.item', verbose_name='наименование'),
        ),
    ]
